### ISSUE TITLE
Revisiting King Markov’s Islands Section

### ISSUE THREAD

**Issue by rajesh06** [pford221/mcmc_algorithms#2]
First bullet: comma should be after "which" rather than before
Third bullet seems like it needs a slight reword: perhaps "time**s** spent on **each** island"

first paragraph after Normal, suggest
The proposal distribution is ~~a~~ separate and distinct ~~distribution~~ from either the prior or posterior distribution for the parameter. (I found this to be easier to read.)

In the last sentence of the paragraph that starts with "By _try_" suggest using "of Bayes' formula" to follow the first two instances of "numerator" rather than the last two.

I have one more suggestion in this section but will file a separate issue for that.

**Comment by pford221** [comment]
Made all these changes.
