### ISSUE TITLE
Revisiting King Markov’s Islands

### ISSUE THREAD

**Issue by rajesh06** [pford221/mcmc_algorithms#3]
I struggled a bit trying to parse the  the paragraph that follows the bulleted list.  There were several reasons for my struggles, but I think (but am not certain) that one of those reasons was that \theta_prop is a random variable while \theta_curr is a (fixed) parameter. 

I don't have a great suggestion but would offer the following:

Change:
To decide which tiny island to visit next, which we denote as \theta_prop, King Markov will need a more general proposal distribution than only being able to move to adjacent islands. Such a proposal distribution should give him the potential to visit any island from any other island. The Metropolis algorithm calls for this proposal distribution to be a normal distribution centered at the current parameter value, \theta_curr, and a user-specified variance, \sigma^2.

To:
In order to be able to visit any island from any other island, King Markov will need a more general proposal distribution than one that only allows movements to adjacent islands. We denote the candidate island **\theta_prop**. The Metropolis algorithm calls for **\theta_prop** to be sampled from a Normal proposal distribution centered at the current parameter value, \theta_curr, with user-specified variance, \sigma^2.

[Then bold \theta_prop in the distribution notation that follows]

As with any of my suggestions, feel free to reject, It's your work - not mine.

**Comment by pford221** [comment]
Adjusted. Thanks.
