### ISSUE TITLE
Final suggestions through the middle of page 8

### ISSUE THREAD

**Issue by rajesh06** [pford221/mcmc_algorithms#4]
Third bullet from the bottom on page 3
Suggestion: Change "non-informative relative to" to "less informative than" 
Reason: It seems to me that "non-informative" is at least a "quasi-defined" term

Top of Page 4
Suggestion: Change "(rnorm)" be either deleting or changing to "(using the `rnorm` function)"
Reason: I don't believe that rnorm is short for "standard normal proposal distribution" which is what is implied by current syntax.

Top of Page 8:
Suggest flipping the x and y axis in the plots so it looks like a traditional chain. (I recognize that this may conflict with the noted inspiration for the Figure.)

Also consider adding to each plot:

    abline(h = c(0.9, 13 / 41), col = c('red', 'green'))

(substitute `v = ` for `h = ` if you keep the current orientation.)

FYI - This is as far as I've gotten in the Note

**Comment by pford221** [comment]
Hey Raj, 

When adding `ablines` to Figure 4, what is the rationale for showing the MLE for `theta`? I think it might make more sense to show the mode of the posterior.

Thanks,
Patrick

**Comment by rajesh06** [comment]
My only thought was to show the the movement from the seed towards the data (represented by the MLE). I can see the logic of having posterior mode as well since that is ultimately where the chain (should) end up. 

Ultimately, I just think the `abline`s will be helpful so that the reader can see the "distance traveled from the seed value.' In that sense, the line at the seed is probably the more important line but the "destination" line (post. mode or MLE) is probably helpful as a visual boundary.

Thanks

**Comment by pford221** [comment]
Cool. Yeah, I'll add something like that.

This is working well for me, but I feel bad for you having to be so specific about where the suggestions are. Would it be easier to produce a Word Document of the paper (the formatting will be a bit off but that's OK) and then you can just make your suggested changes by using Track Changes? That way you don't have to specify hard-to-describe locations like _4th paragraph, 2nd sentence, second to last word, etc._ 

Thanks,
Patrick

**Comment by rajesh06** [comment]
No worries - I am getting a lot out of reading the note. 

I have just started getting into MCMC and probably  average one analysis per month - though I expect that pace to pick up as I get through the year-end crunch.

I think this is going to be a very difficult topic for our candidates.

**Comment by pford221** [comment]
Done.
